---
  - name: Installing ansible
    hosts: util 
    become: true
    vars: 
      nginx_service_state: started
      nginx_service_enabled: yes
    roles:
    - geerlingguy.nginx
    task:
    - name: Opening Firewall port 80
      become: true
      command: firewall-cmd --add-port:80/tcp --permanent
    - name: Reloading firewall
      become: true
      command: firewall-cmd --reload